package io.reticulum;

import io.reticulum.identity.Identity;
import org.apache.commons.codec.DecoderException;
import org.apache.commons.codec.binary.Hex;
import org.bouncycastle.crypto.digests.SHA256Digest;
import org.bouncycastle.crypto.generators.HKDFBytesGenerator;
import org.bouncycastle.crypto.params.HKDFParameters;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.List;

import static io.reticulum.constant.IdentityConstant.AES128_BLOCKSIZE;
import static io.reticulum.constant.IdentityConstant.KEYSIZE;
import static io.reticulum.constant.IdentityConstant.TOKEN_OVERHEAD;
import static io.reticulum.constant.ReticulumConstant.IFAC_SALT;
import static io.reticulum.utils.IdentityUtils.concatArrays;
import static io.reticulum.utils.IdentityUtils.fullHash;
import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class IdentityTest {

    @Test
    void sign() {
    }

    @Test
    void signAndValidateIfaceKey() throws IOException {
        var netName = "name";
        var netKey = "passfrase";

        var ifacOriginHash = fullHash(concatArrays(fullHash(netName.getBytes(UTF_8)), fullHash(netKey.getBytes(UTF_8))));

        var hkdf = new HKDFBytesGenerator(new SHA256Digest());
        hkdf.init(new HKDFParameters(ifacOriginHash, IFAC_SALT, new byte[0]));
        var ifacKey = new byte[64];
        hkdf.generateBytes(ifacKey, 0, ifacKey.length);

        var identity = Identity.fromBytes(ifacKey);

        var message = fullHash(ifacKey);
        var signature = identity.sign(message);
        var actual = Hex.encodeHexString(signature);
        var expected = "f719fae770705c43b6047fd919fc89b4f4a8655477ef7ee13cb14121011afc571d049990a71a04457d8600e60afdca93f96de02216ad52a32eff23e82807840e";

        assertEquals(expected, actual);

        assertTrue(identity.validate(signature, message));
    }

    @Test
    void validate() {
    }

    /**
     * Identity used for the reference vectors below. Its ciphertexts were
     * generated by Python RNS 1.5.2 from this same private key.
     */
    private static final String REFERENCE_PRIVATE_KEY =
            "80d455d6a5715f93a503c0f2b9c56aff7a94c2524ff8bb0042a5ca7fb3196c78"
            + "00064603a3559dd3668f7dc900d7b9e15432cf830a28d45078c9335d26b5423c";

    @Test
    void encryptAndDecrypt() {
        var identity1 = new Identity(true);
        var identity2 = new Identity(false);
        identity2.loadPublicKey(identity1.getPublicKey());

        var plaintext = "passfrase".getBytes(UTF_8);
        var token = identity2.encrypt(plaintext);

        // 32 byte ephemeral public key + 16 byte padded plaintext + 48 byte token overhead
        assertEquals(KEYSIZE / 8 / 2 + AES128_BLOCKSIZE + TOKEN_OVERHEAD, token.length);

        assertEquals("passfrase", new String(identity1.decrypt(token)));
    }

    @Test
    @DisplayName("Decrypts an AES-256 identity ciphertext produced by Python RNS 1.5.2")
    void decrypt() throws DecoderException {
        var encrypted = "fb74a3c40ed34a89f22cc76684e58c8d806f5900b03c0404efb040b62afa6206"
                + "35b410497785e192bf80806ef06ef3e0ca0ded1b7c9708bc84bed845fb60b60b"
                + "7fadd8b2b8c4b0f43c930ef005b513f03d38e8e72a91333d28ab65de2017544e";

        var id1 = Identity.fromBytes(Hex.decodeHex(REFERENCE_PRIVATE_KEY));
        var decrypted = id1.decrypt(Hex.decodeHex(encrypted));

        assertEquals("passfrase", new String(decrypted));
    }

    @Test
    @DisplayName("Decrypts a multi-block AES-256 identity ciphertext from Python RNS 1.5.2")
    void decryptMultiBlock() throws DecoderException {
        var encrypted = "fbbafbdd5c3c8b793a517c1d19234bc47fd53064c6240b4e7cbeda474f5a0152"
                + "e73d0f4e84b1d1a395094abac706b2cf0868d86c59a2f6dabed751f6c1d2f052"
                + "e7eaebc618b43bdb1ec13c8cd0a95ba07b022af53121f682d560aa42dde8d7ca"
                + "08ab65de22ddbd5e32cb238b6be4cf2b1fe7f1a8631f4e83b5aa4a22b171c665";

        var id1 = Identity.fromBytes(Hex.decodeHex(REFERENCE_PRIVATE_KEY));
        var decrypted = id1.decrypt(Hex.decodeHex(encrypted));

        assertEquals("The quick brown fox jumps over the lazy dog", new String(decrypted));
    }

    /**
     * A ratchet-encrypted ciphertext from Python RNS 1.5.2. Decryption must
     * succeed with the ratchet key and return null with the identity's base key.
     * <p>
     * The null case is the one that matters: it only holds because
     * {@code Token.decrypt} verifies the HMAC before decrypting. Relying on a
     * PKCS7 padding failure instead would let a wrong key through roughly one
     * time in 256, returning garbage rather than null.
     */
    @Test
    @DisplayName("Ratchet ciphertext from Python RNS 1.5.2 decrypts only with the ratchet key")
    void decryptWithRatchet() throws DecoderException {
        var ratchetPrv = "502df4ab79125ee1b77fd92975ca2e02b9fe740324e37339ad447c0939eb646a";
        var encrypted = "b8564239396f518f91cd7385dd6a2ec3b5e10bd5cd8746cb6192770bfb12142b"
                + "c29e5d988eccf4409dce5c7813515e73ce2d9fc7d919ea4c54b177eed9e6818f"
                + "ebe1162a8c50cb7555c467b1708b983f90ce5ab5c538c98688ced8d941c28eff"
                + "a3cefcb24f75735de0c4d0e18e83417d";

        var id1 = Identity.fromBytes(Hex.decodeHex(REFERENCE_PRIVATE_KEY));
        var ciphertext = Hex.decodeHex(encrypted);

        var withRatchet = id1.decrypt(ciphertext, List.of(Hex.decodeHex(ratchetPrv)), false);
        assertEquals("ratcheted payload", new String(withRatchet));

        assertNull(id1.decrypt(ciphertext), "base key must not decrypt a ratcheted token");
    }

    @Test
    @DisplayName("Identity hash matches Python RNS 1.5.2 for the reference key")
    void referenceIdentityHash() throws DecoderException {
        var id1 = Identity.fromBytes(Hex.decodeHex(REFERENCE_PRIVATE_KEY));

        assertEquals("c3493380191234476fef6a6ee4884554", Hex.encodeHexString(id1.getHash()));
    }
}